// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-6KdD4WKMN80pbAWpELHVvsZKeRjToo',
    appId: '1:269197339207:web:d1240005de3e32d099df62',
    messagingSenderId: '269197339207',
    projectId: 'axora-we',
    authDomain: 'axora-we.firebaseapp.com',
    storageBucket: 'axora-we.firebasestorage.app',
    measurementId: 'G-MW96WHJR17',
    databaseURL: 'https://axora-we-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApJu5ns2-0F2GL5gWBZaVxuhJ65Bcu1qI',
    appId: '1:269197339207:android:d7f0bf5d498e041f99df62',
    messagingSenderId: '269197339207',
    projectId: 'axora-we',
    storageBucket: 'axora-we.firebasestorage.app',
    databaseURL: 'https://axora-we-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJu5ns2-0F2GL5gWBZaVxuhJ65Bcu1qI',
    appId: '1:269197339207:ios:d783532d9cb8a0f099df62',
    messagingSenderId: '269197339207',
    projectId: 'axora-we',
    storageBucket: 'axora-we.firebasestorage.app',
    iosBundleId: 'com.rr.axora.axora',
    databaseURL: 'https://axora-we-default-rtdb.firebaseio.com',
  );
}
