// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7cc_fRJ_Nw46STdCtyyHxgJq3Ohlopk',
    appId: '1:906770746320:web:95ab2ddbd057c5bf4bc7d5',
    messagingSenderId: '906770746320',
    projectId: 'axora-5039',
    authDomain: 'axora-5039.firebaseapp.com',
    storageBucket: 'axora-5039.firebasestorage.app',
    measurementId: 'G-SLRQ60QJT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MkkNGH40eAzjOxuekspbIpN_FQhQXv0',
    appId: '1:906770746320:android:8aede31e4dc475a84bc7d5',
    messagingSenderId: '906770746320',
    projectId: 'axora-5039',
    storageBucket: 'axora-5039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyg_XpQ2hVAFpaj30HnRVfw-Ig7OjGc2A',
    appId: '1:906770746320:ios:11f83c221f8d392c4bc7d5',
    messagingSenderId: '906770746320',
    projectId: 'axora-5039',
    storageBucket: 'axora-5039.firebasestorage.app',
    iosBundleId: 'com.rr.axora.axora',
  );
}
